// test/icon-subset-guard.test.js
//
// Guard for the fundamental-styles icon subset (issue #1779).
//
// hugo/assets/css/fundamental-styles-icon.css is a SUBSET of the upstream
// fundamental-styles icon.css, generated by scripts/build-icon-subset.cjs to
// contain only the sap-icon-- glyph classes actually used in the source tree.
// If someone adds a new `sap-icon--<glyph>` usage but forgets to regenerate the
// subset (`npm run build:icon-subset`), that glyph would render blank in prod.
// This test fails CI in that case.
//
// It also locks in the de-dup: sap-fundamental.css must NOT re-bundle the glyph
// classes (that duplication was the ~78 KiB × 2 unused-CSS finding).

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const { scanUsedGlyphs } = require('../scripts/lib/used-sap-icons.cjs');

const REPO_ROOT = join(import.meta.dirname, '..');
const read = (p) => readFileSync(join(REPO_ROOT, p), 'utf8');

const SUBSET = read('hugo/assets/css/fundamental-styles-icon.css');
const BUNDLE = read('hugo/assets/css/sap-fundamental.css');

// Glyph classes defined in the committed subset (`.sap-icon--NAME:before{content:...}`).
const subsetGlyphs = new Set(
  [...SUBSET.matchAll(/\.sap-icon--([a-z0-9-]+):before\{content:/g)].map((m) => m[1]),
);

// Classes used in source that have NO glyph in upstream fundamental-styles, so
// they cannot be subsetted and already render blank today (pre-existing gaps,
// not a regression introduced by the subset). Keep this list tiny + documented.
//   - gift: used on the internal event scanner "Claim Prize" button
//     (hugo-apps/src/scanner-vue/ScannerApp.vue); no `gift` glyph exists in
//     fundamental-styles 0.41.7. Tracked separately from #1779.
const KNOWN_MISSING_UPSTREAM = new Set(['gift']);

describe('#1779 — icon subset covers all used sap-icon-- glyphs', () => {
  const { glyphs: used, byFile } = scanUsedGlyphs(REPO_ROOT);

  it('scans at least the known homepage/navigator/explore usages', () => {
    // Sanity: the scanner found real usage (guards against a broken scan silently
    // reporting an empty set, which would make the coverage check vacuous).
    expect(used).toEqual(expect.arrayContaining(['course-book', 'lightbulb', 'ai']));
  });

  it('every used glyph is present in the subset (or a documented upstream gap)', () => {
    const uncovered = used.filter(
      (g) => !subsetGlyphs.has(g) && !KNOWN_MISSING_UPSTREAM.has(g),
    );
    const detail = uncovered
      .map((g) => `${g} (in ${Object.entries(byFile).filter(([, gs]) => gs.includes(g)).map(([f]) => f).join(', ')})`)
      .join('; ');
    expect(
      uncovered,
      `Used sap-icon-- glyph(s) missing from the subset: ${detail}. ` +
        `Run \`npm run build:icon-subset\` and commit the regenerated CSS.`,
    ).toEqual([]);
  });

  it('the subset stays tight (not the full ~800-glyph upstream set)', () => {
    // Upper bound well above today's 9, far below the ~684 SAP-icons glyphs.
    expect(subsetGlyphs.size).toBeGreaterThan(0);
    expect(subsetGlyphs.size).toBeLessThan(60);
  });

  it('keeps the structural base rule', () => {
    expect(SUBSET).toMatch(/\[class\*=sap-icon\]:before\{font-family:SAP-icons/);
  });
});

describe('#1779 — glyphs are de-duplicated (not re-bundled)', () => {
  it('sap-fundamental.css does not re-ship sap-icon-- glyph content rules', () => {
    const glyphContentRules = BUNDLE.match(/\.sap-icon--[a-z0-9-]+:before\{content:/g) || [];
    expect(glyphContentRules).toEqual([]);
  });

  it('sap-fundamental.src.css no longer imports the full icon.css', () => {
    const src = read('hugo/assets/css/sap-fundamental.src.css');
    expect(src).not.toMatch(/@import 'fundamental-styles\/dist\/icon\.css'/);
  });
});
