// Themed background scenes for the Devtoberfest selfie composer (#1520).
// "Generative" background = curated vector art (generated by scripts/gen-backgrounds.mjs),
// composited behind the cut-out person on a dedicated bottom-most Konva layer.
// The person cutout comes from the existing imgly segmentation (Tier 1 #1514).

export interface BackgroundDef {
  id: string
  label: string
  file: string // basename under `${imgBase}/backgrounds/`; URL is `${imgBase}/backgrounds/${file}.png`
}

export const BACKGROUNDS: BackgroundDef[] = [
  { id: 'key-visual-josh',      label: 'Key visual (Josh)',  file: 'key-visual-option-josh-16-9' },
  { id: 'key-visual-nora',      label: 'Key visual (Nora)',  file: 'key-visual-option-nora-16-9' },
  { id: 'terminal',        label: 'Terminal',      file: 'terminal' },
  { id: 'speaker-backdrop-1',   label: 'Speaker backdrop 1', file: 'speaker-backdrop-option1-16-9' },
  { id: 'speaker-backdrop-2',   label: 'Speaker backdrop 2', file: 'speaker-backdrop-option2-16-9' },
]

// Picker order — 'none' (no themed background) first, then each scene.
export const BACKGROUND_IDS: string[] = ['none', ...BACKGROUNDS.map((b) => b.id)]

export function backgroundUrl(imgBase: string, file: string): string {
  return `${imgBase}/backgrounds/${file}.png`
}
