// Themed background scenes for the Devtoberfest selfie composer (#1520).
// "Generative" background = curated vector art (generated by scripts/gen-backgrounds.mjs),
// composited behind the cut-out person on a dedicated bottom-most Konva layer.
// The person cutout comes from the existing imgly segmentation (Tier 1 #1514).

export interface BackgroundDef {
  id: string
  label: string
  file: string // basename under `${imgBase}/backgrounds/`; URL is `${imgBase}/backgrounds/${file}.png`
}

export const BACKGROUNDS: BackgroundDef[] = [
  { id: 'pumpkin-patch',   label: 'Pumpkin patch', file: 'pumpkin-patch' },
  { id: 'teched-stage',    label: 'On stage',      file: 'teched-stage' },
  { id: 'terminal',        label: 'Terminal',      file: 'terminal' },
  { id: 'autumn-gradient', label: 'Autumn',        file: 'autumn-gradient' },
  { id: 'starfield',       label: 'Starfield',     file: 'starfield' },
]

// Picker order — 'none' (no themed background) first, then each scene.
export const BACKGROUND_IDS: string[] = ['none', ...BACKGROUNDS.map((b) => b.id)]

export function backgroundUrl(imgBase: string, file: string): string {
  return `${imgBase}/backgrounds/${file}.png`
}
