// Workspace-first: full surface (incl. test seams) in local dev; bundle fallback at CF deploy.
let mod;
try { mod = await import('@tutorials/content/content-store.js'); }
catch { mod = await import('./_shared/content.bundle.mjs'); }
export const toBuffer = mod.toBuffer;
export const isCatalogSlug = mod.isCatalogSlug;
export const dropCatalogSlugs = mod.dropCatalogSlugs;
export const recomputeTutorialProgress = mod.recomputeTutorialProgress;
export const triggerPostPublishEmbeddings = mod.triggerPostPublishEmbeddings;
export const DEFAULT_CONTENT_CACHE_TTL_MS = mod.DEFAULT_CONTENT_CACHE_TTL_MS;
export const ContentCache = mod.ContentCache;
export const invalidateRenderCache = mod.invalidateRenderCache;
export const invalidateContentCache = mod.invalidateContentCache;
export const createContentHandlers = mod.createContentHandlers;
export const contentAuthMiddleware = mod.contentAuthMiddleware;
export const publishHandler = mod.publishHandler;
export const serveHandler = mod.serveHandler;
export const markdownServeHandler = mod.markdownServeHandler;
export const hashesHandler = mod.hashesHandler;
export const sourceHashesHandler = mod.sourceHashesHandler;
export const getTutorialSource = mod.getTutorialSource;
export const navHandler = mod.navHandler;
export const rollbackHandler = mod.rollbackHandler;
export const orphanPurgeHandler = mod.orphanPurgeHandler;
export const beginHandler = mod.beginHandler;
export const appendHandler = mod.appendHandler;
export const commitHandler = mod.commitHandler;
export const abortHandler = mod.abortHandler;
export const pipelineLogFailureHandler = mod.pipelineLogFailureHandler;
export const pageServeHandler = mod.pageServeHandler;
export const authorServeHandler = mod.authorServeHandler;
export const advocateServeHandler = mod.advocateServeHandler;
