export interface TutorialFrontmatter {
  time: number
  author_name: string
  author_profile: string
  tags: string[]
  primary_tag: string
  parser?: string
  title?: string
  description?: string
  /**
   * [#173] Per-step overrides for the OS-classifier in
   * `scripts/parsers/options.ts`. Keyed by slugified step heading.
   * `'os'` forces the OS picker (lookup label via classifier rules);
   * `'regular'` keeps the legacy option-tabs shortcode even if labels
   * heuristically look OS-shaped.
   */
  osOverrides?: Record<string, 'os' | 'regular'>
}

/**
 * Canonical question-type discriminators. Source of truth for the
 * `ValidationQuestion.type` union — import these instead of writing the
 * string literals so a future schema drift (`'free-text'`, `'long-text'`)
 * surfaces at the type-check level rather than as silently-broken
 * anti-leak filters.
 *
 * Test fixtures intentionally use the literals as inputs and don't
 * import these constants.
 */
export const QUESTION_TYPE_TEXT = 'text' as const
export const QUESTION_TYPE_MCQ = 'multiple-choice' as const
export type QuestionType = typeof QUESTION_TYPE_TEXT | typeof QUESTION_TYPE_MCQ

export interface ValidationQuestion {
  id: string
  question: string
  type: 'multiple-choice' | 'text'
  options?: string[]
  // CHANGED: correctAnswer is now optional. Omitted for AI-graded
  // questions (issue #209) — the reference answer ships server-side
  // via ValidateAnswerSpecs and never enters the public Hugo
  // frontmatter or <script id="tutorial-data"> JSON.
  // The hugo-apps consumer (`hugo-apps/src/validation/grading.ts`) defines its own local
  // interface that keeps correctAnswer: string required; AI-graded questions are routed
  // away from gradeAnswers() at the call site (Task 10).
  correctAnswer?: string
  // NEW — opted in via ###Grading: ai-judged OR via regex rule types (issue #209).
  aiGrading?: boolean
  // [#208] Set true when this question was generated by the AI quiz
  // generator. Joins to the eval harness; ships in public frontmatter
  // for MCQ + sidecar for text. Indistinguishable from hand-authored
  // questions to the validation widget.
  aiAuthored?: boolean
  /**
   * [#208] Build-time sentinel set by the AI quiz generator (`srv/lib/ai-quiz-generator.js`)
   * for AI-authored text questions. Carries the reference answer through
   * the cache + eval harness; ALWAYS stripped before public Hugo
   * frontmatter emission (`materializeForPipeline` in
   * `scripts/lib/expand-ai-authored.ts` moves it to `correctAnswer` for
   * the pipeline shape, and the bridge strip in `scripts/fetch-tutorials.ts`
   * deletes `correctAnswer` again before frontmatter emit).
   *
   * Should NEVER appear in:
   *  - Hugo frontmatter / `<script id="tutorial-data">` JSON
   *  - Network responses
   *  - Logs
   *
   * Only legitimate readers: `materializeForPipeline`, the eval CSV emitter
   * (`scripts/evaluate-ai-quizzes.ts`), and the cache JSON file at
   * `.tutorial-cache/<slug>.ai-quiz-cache.json`.
   */
  __aiCorrectAnswer?: string
}

export interface TutorialStep {
  number: number
  title: string
  content: string
  validation?: ValidationQuestion[]
  codeCheck?: PublicCodeCheckSpec

  // Issue #172 PR 3 — step-level branches (populated by branches.ts pre-pass
  // before parseV2Steps walks the rewritten body; merged onto the parent step
  // entry by index in scripts/fetch-tutorials.ts).
  branchGroup?: string          // e.g. "deployment"
  branchPointId?: string        // e.g. "1-deployment"
  branches?: Array<{
    key: string
    label: string
    condition: string | null
    embeddingHint: string | null
    steps: Array<{ title: string; body: string }>
  }>

  // Issue #172 PR 3 — skip-runs (per-step frontmatter, no parser changes;
  // /api/branches/decide reads these at runtime to compute skip recommendations).
  skipIf?: string               // condition expression
  skipLabel?: string            // optional override for the [Skip] button text
  skipReason?: string           // optional human-readable reason string
}

export interface ParsedTutorial {
  slug: string
  title: string
  description: string
  time: number
  level: string
  tags: string[]
  primaryTag: string
  author: string
  authorProfile: string
  repo: string
  branch: string
  youWillLearn: string[]
  prerequisites: string
  steps: TutorialStep[]
}

export interface TutorialNavEntry {
  slug: string
  title: string
  description: string
  time: number
  level: string
  stepCount: number
  primaryTag: string
  displayTags: string[]
  displayTagSlugs: string[]
  repo?: string
  branch?: string
  missionId?: number
  missionTitle?: string
  groupId?: number
  groupTitle?: string
  missionSlug?: string
  groupSlug?: string
  prev: string | null
  next: string | null
  recommendations?: string[]
  // ISO timestamp of the oldest commit on the tutorial markdown file —
  // used by the navigator to render a "NEW" badge for tutorials authored in the last 31 days.
  createdAt?: string
  /**
   * [#172] PR 2 Task 7. Mission-level alt-groups copied from the mission's
   * MissionMeta.altGroups so the tutorial page's frontmatter (and thus the
   * `mission-side-nav.html` partial rendering on this tutorial page) can
   * render branch chips without round-tripping to the mission page (which
   * doesn't exist as a static `.md` — it's SSR'd by catalog-renderer).
   */
  missionAltGroups?: AltGroup[]
}

export interface GroupRef {
  id: number
  title: string
  slug: string
  missionId: number
  tutorials: string[]
}

export interface MissionMeta {
  id: number
  title: string
  slug: string
  groups: GroupRef[]
  /**
   * [#172] Branched-mission alt-groups. Set when a mission's CompletionPathItems
   * carry altGroupKey/altGroupLabel/altCondition. PR 3's hydration island reads
   * these from `_nav.json` to render branch tabs.
   */
  altGroups?: AltGroup[]
}

export interface NavData {
  tutorials: TutorialNavEntry[]
  missions: MissionMeta[]
  groups: GroupRef[]
}

export const RAW_BASE_URL = 'https://raw.githubusercontent.com'

export interface GitHubContributor {
  name: string
  login: string
  avatarUrl: string
}

export interface Mission {
  imsId: number
  title: string
  slug: string
  description: string
  level: string
  time: number
  icon: string
  tasksCount: number
  categorySlugs?: string[]
}

export interface HierarchyGroup {
  imsId: number
  title: string
  slug: string
  description: string
  tutorialSlugs: string[]
  categorySlugs?: string[]
  /**
   * [#172] Alt-group branches collected from CompletionPathItems on the
   * underlying CompletionPath. Optional — only present when the path has at
   * least one alt-group fork.
   */
  altGroups?: AltGroup[]
}

export interface MissionHierarchy {
  missionImsId: number
  groups: HierarchyGroup[]
  tutorialSlugs: string[]
  /**
   * [#172] Lifted from the synthetic single-path group when /build/catalog
   * collapses an isFlat mission. Consumers should look here AND on
   * `groups[*].altGroups` (only one of the two will be populated for a given
   * mission).
   */
  altGroups?: AltGroup[]
}

/** [#172] One branch within an alt-group (e.g. "HANA Cloud" alongside "PostgreSQL"). */
export interface AltGroupBranch {
  key: string
  label: string
  tutorialSlug: string
  condition: string | null
}

/** [#172] An alt-group is a single fork-point in a mission with N branches. */
export interface AltGroup {
  groupKey: string
  branches: AltGroupBranch[]
}

export interface StandaloneGroup {
  imsId: number
  title: string
  slug: string
  description: string
  tutorialSlugs: string[]
  categorySlugs?: string[]
}

/** A single entry from the top-level categories[] array in /build/catalog. */
export interface CategoryMeta {
  slug: string
  label: string
  sortOrder: number
  activeCount: number
}

/** Slim per-tutorial metadata from /build/catalog (categorySlugs only — nav data lives in TutorialNavEntry). */
export interface CatalogTutorialMeta {
  slug: string
  categorySlugs: string[]
}

// Full CodeCheckSpec — used by the publish pipeline. NEVER ship to the
// client; the referenceSolution field is author-only.
export interface CodeCheckSpec {
  stepNumber: number
  goal: string             // required
  language?: string
  hints?: string[]
  referenceSolution?: string
}

// Trimmed shape that ships in Hugo frontmatter / data-* attributes.
// Includes hasReference flag so the grader can know one exists without
// the spec having to ship it.
export interface PublicCodeCheckSpec {
  goal: string
  language?: string
  hints?: string[]
  hasReference: boolean
}
