import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { pathToFileURL } from 'node:url';

// scripts/seed-sitemap-from-deployed.ts
//
// Preserves /sitemap.xml across catalog-only rebuilds — same wipe class as the
// /browse/ (seed-browse-from-deployed.ts) and /authors/ (seed-authors-from-
// deployed.ts) preserve steps. Reported 2026-09-03 by the Intelligent Search
// Data Crawling team (crawled docs ~1700 → ~1500; live sitemap held ~180 links).
//
// THE BUG
//   /sitemap.xml is served from HANA as the `page-sitemap.xml` blob (srv/lib/
//   page-key-map.js IN_SCOPE_PAGES). scripts/publish-content.ts merges that
//   page-* blob into the publish set via discoverPageFiles() whenever the run is
//   NOT slug-scoped. The rebuild-content workflow skips "Fetch tutorials" in
//   catalog-only mode, so hugo/content/tutorials is empty, the Hugo build bakes a
//   sitemap with NO /tutorials/ URLs, and publishing that tutorial-less blob
//   WIPES the live sitemap down to its non-tutorial pages (~180 URLs).
//
// WHY NOT just regenerate the sitemap in catalog-only?
//   The sitemap is generated by Hugo iterating site.Pages — it needs the ~1.4k
//   tutorial content pages present at build time. Those come ONLY from the
//   GitHub tutorial-markdown fetch that catalog-only deliberately skips (it's the
//   fast admin-edit path). Running the fetch would defeat the mode.
//
// THE FIX (this script)
//   In catalog-only mode, AFTER the Hugo build (unlike seed-browse/seed-authors,
//   which re-hydrate build INPUTS before the build), overwrite the freshly-baked
//   (tutorial-less) hugo/public/sitemap.xml with the sitemap the approuter is
//   CURRENTLY serving at /sitemap.xml. That deployed sitemap already carries the
//   full tutorial <urlset> from the last full rebuild, so the publish step
//   carries it forward verbatim instead of shipping a wiped one. The
//   check-sitemap-tutorials.cjs guard then runs as the fail-closed net.
//
// FAIL-SAFE
//   If the deployed sitemap can't be fetched, isn't a <urlset>, or names zero
//   /tutorials/ URLs, this script EXITS NON-ZERO without writing — deliberately
//   FAILING the catalog-only rebuild rather than shipping a wiped sitemap. A hard
//   failure is visible and recoverable (re-run mode=full); a silent wipe is the
//   exact incident this fixes. The one acceptable "empty" case (a fresh/seed env
//   with no tutorials yet) is handled by ALLOW_EMPTY_SITEMAP=1.

const APPROUTER_URL = (process.env.APPROUTER_URL || '').replace(/\/+$/, '');
const OUT_PATH = join('hugo', 'public', 'sitemap.xml');
const ALLOW_EMPTY = process.env.ALLOW_EMPTY_SITEMAP === '1';

// Count <loc> entries under /tutorials/<slug>. Kept in sync with
// scripts/check-sitemap-tutorials.cjs countTutorialLocs (this file can't import
// the .cjs cleanly under tsx without pulling its CLI, so the tiny matcher is
// duplicated; both are covered by unit tests). Exported for the unit test.
export function countTutorialLocs(xml: string): number {
  if (typeof xml !== 'string' || xml.length === 0) return 0;
  let count = 0;
  const re = /<loc>\s*([^<]+?)\s*<\/loc>/gi;
  let m: RegExpExecArray | null;
  while ((m = re.exec(xml)) !== null) {
    const pathOnly = m[1].replace(/^https?:\/\/[^/]+/i, '');
    if (/^\/tutorials\/[^/][^<]*$/i.test(pathOnly)) count += 1;
  }
  return count;
}

function die(msg: string): never {
  console.error(`[seed-sitemap] FAILED: ${msg}`);
  console.error('[seed-sitemap] Refusing to proceed — a catalog-only rebuild must not ship a sitemap with no /tutorials/ URLs.');
  console.error('[seed-sitemap] Recover by re-running the rebuild with mode=full, or set ALLOW_EMPTY_SITEMAP=1 if the catalog is genuinely empty.');
  process.exit(1);
}

async function main() {
  if (!APPROUTER_URL) die('APPROUTER_URL is not set');

  let xml: string;
  try {
    const res = await fetch(`${APPROUTER_URL}/sitemap.xml`, { redirect: 'follow' });
    if (!res.ok) die(`GET ${APPROUTER_URL}/sitemap.xml returned ${res.status}`);
    xml = await res.text();
  } catch (err) {
    die(`could not fetch ${APPROUTER_URL}/sitemap.xml — ${err instanceof Error ? err.message : err}`);
  }

  if (!xml.includes('<urlset')) {
    die('deployed /sitemap.xml is not a <urlset> document (got an error page or redirect body?)');
  }

  const tutorialCount = countTutorialLocs(xml);
  if (tutorialCount === 0 && !ALLOW_EMPTY) {
    die('deployed /sitemap.xml has zero /tutorials/ URLs. This env has no populated sitemap to preserve — a previous catalog-only rebuild may have already wiped it. Re-run with mode=full to regenerate.');
  }

  if (!existsSync(dirname(OUT_PATH))) mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, xml, 'utf-8');
  console.log(`[seed-sitemap] wrote ${xml.length} bytes to ${OUT_PATH} (preserved from deployed ${APPROUTER_URL}/sitemap.xml, ${tutorialCount} /tutorials/ URLs).`);
}

// Only run main() when invoked directly (not when imported by the unit test).
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch(e => { console.error(e); process.exit(1); });
}
